export const restaurantData = [
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "376052",
          name: "NIC Ice Creams",
          uuid: "baa984bd-6648-43d1-849d-3df3cd722126",
          city: "13",
          area: "Panampilly Nagar",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "91d6dda411b108965541c16ac1cfe2bc",
          cuisines: ["Ice Cream", "Desserts"],
          tags: [],
          costForTwo: 12000,
          costForTwoString: "₹120 FOR TWO",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          slaString: "21 MINS",
          lastMileTravel: 5.5,
          slugs: {
            restaurant:
              "nic-natural-ice-creams-parambithara-road-panampilly-nagar",
            city: "kochi",
          },
          cityState: "13",
          address:
            "Shop no 55/63-B (South-West Portion) Parambithara Road, Panampilly Nagar, Cochin, Kerala-682036, Ernakulam, Kerala-682036",
          locality: "Parambithara Road",
          parentId: 6249,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "FLAT125 off",
            shortDescriptionList: [
              {
                meta: "FLAT125 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "FLAT125 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹125 OFF",
            shortDescriptionList: [
              {
                meta: "Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "FLAT125 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 6500,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 6500,
            message: "",
            title: "Delivery Charge",
            amount: "6500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "376052",
            deliveryTime: 21,
            minDeliveryTime: 21,
            maxDeliveryTime: 21,
            lastMileTravel: 5.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.6",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "339289",
          name: "Absolute Shakes",
          uuid: "3950cbff-6d6e-4afd-95d8-e987f6c95475",
          city: "13",
          area: "Panampilly Nagar",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "wyzdnjqpxzgyy01pdf2v",
          cuisines: ["Beverages", "Juices", "Desserts"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          slaString: "38 MINS",
          lastMileTravel: 5.5,
          slugs: {
            restaurant: "absolute-milkshakes-panampilly-nagar-panampilly-nagar",
            city: "kochi",
          },
          cityState: "13",
          address:
            "MASH RESTOCAFE,55/402-B,4th Cross Road,Panampilly Nagar,Kochi, Eranakulam Circle, Ernakulam(Kerala) -682036",
          locality: "Eranakulam Circle",
          parentId: 26779,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "30% off",
            shortDescriptionList: [
              {
                meta: "30% off | Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "30% off up to ₹75 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "30% OFF",
            shortDescriptionList: [
              {
                meta: "Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "30% off up to ₹75 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 6500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 6500,
            message: "",
            title: "Delivery Charge",
            amount: "6500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "339289",
            deliveryTime: 38,
            minDeliveryTime: 38,
            maxDeliveryTime: 38,
            lastMileTravel: 5.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.6",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "517890",
          name: "HEARTH KITCHEN",
          uuid: "a558c647-8bf6-41e1-a4f2-78d6a2fbb3a9",
          city: "13",
          area: "Panampilly Nagar",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "ljtbcaigrbn3pyz8nyit",
          cuisines: ["Pizzas"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          slaString: "31 MINS",
          lastMileTravel: 5.599999904632568,
          slugs: {
            restaurant: "hearth-kitchen-panampilly-nagar-panampilly-nagar",
            city: "kochi",
          },
          cityState: "13",
          address:
            "HEARTH KITCHEN PVT LTD CC 55/410 Fourth Cross Road Panampilly Nagar, Thrikkakara Circle, Ernakulam, Kerala - 682036",
          locality: "Thrikkakara",
          parentId: 309577,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 6500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 6500,
            message: "",
            title: "Delivery Charge",
            amount: "6500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "517890",
            deliveryTime: 31,
            minDeliveryTime: 31,
            maxDeliveryTime: 31,
            lastMileTravel: 5.599999904632568,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.4",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "451528",
          name: "Haji Ali Juice Centre",
          uuid: "4c129c7b-ee65-439f-8464-4b853a49dd97",
          city: "13",
          area: "Panampilly Nagar",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "pnfx0j3ysogwz1gdmkrg",
          cuisines: ["Juices", "Beverages"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 35,
          minDeliveryTime: 35,
          maxDeliveryTime: 35,
          slaString: "35 MINS",
          lastMileTravel: 5.699999809265137,
          slugs: {
            restaurant: "haji-ali-juice-centre-panampilly-nagar-panampilly-nagar",
            city: "kochi",
          },
          cityState: "13",
          address:
            "55/617-1, Ground  Floor,Sreyas Arcade,  Main Avenue, Panampilly  Nagar, Thrikkakara Circle-682036",
          locality: "Thrikkakara",
          parentId: 17435,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 6500,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 6500,
            message: "",
            title: "Delivery Charge",
            amount: "6500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.6 kms",
          hasSurge: false,
          sla: {
            restaurantId: "451528",
            deliveryTime: 35,
            minDeliveryTime: 35,
            maxDeliveryTime: 35,
            lastMileTravel: 5.699999809265137,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.2",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "339292",
          name: "Pizza Terminal",
          uuid: "2a22ce54-07bb-4ea1-9ae9-853981d78da0",
          city: "13",
          area: "Edapally",
          totalRatingsString: "20+ ratings",
          cloudinaryImageId: "iwh2gjqzqo5cmqkhekvz",
          cuisines: ["Pizzas", "Desserts", "Snacks"],
          tags: [],
          costForTwo: 50000,
          costForTwoString: "₹500 FOR TWO",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          slaString: "37 MINS",
          lastMileTravel: 5.599999904632568,
          slugs: {
            restaurant: "pizza-terminal-edapally-edapally",
            city: "kochi",
          },
          cityState: "13",
          address:
            "Mash Resto Cafe 55/402B, 4th Cross Road, Panampilly Nagar,  Kerala 682036",
          locality: "",
          parentId: 158988,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "30% off",
            shortDescriptionList: [
              {
                meta: "30% off | Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "30% off up to ₹75 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "30% OFF",
            shortDescriptionList: [
              {
                meta: "Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "30% off up to ₹75 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 6500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 6500,
            message: "",
            title: "Delivery Charge",
            amount: "6500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "339292",
            deliveryTime: 37,
            minDeliveryTime: 37,
            maxDeliveryTime: 37,
            lastMileTravel: 5.599999904632568,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.6",
          totalRatings: 20,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "54751",
          name: "Chicking",
          uuid: "39b7da53-b07e-4590-a949-717396a271eb",
          city: "13",
          area: "Shenoys",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "meunlzwaw89dg0oyydst",
          cuisines: [
            "Snacks",
            "Grill",
            "Fast Food",
            "American",
            "Pizzas",
            "Mexican",
            "Beverages",
          ],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          slaString: "34 MINS",
          lastMileTravel: 6.599999904632568,
          slugs: {
            restaurant: "chicking-mg-road-mg-road",
            city: "kochi",
          },
          cityState: "13",
          address:
            "Amritha Towers, KPCC Junction, Mahatma Gandhi Road, Shenoys, Ernakulam, Kerala 682011, India",
          locality: "Mg Road",
          parentId: 251,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "Flat ₹125 off",
            shortDescriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹125 OFF",
            shortDescriptionList: [
              {
                meta: "Use MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 7500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 7500,
            message: "",
            title: "Delivery Charge",
            amount: "7500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "6.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "54751",
            deliveryTime: 34,
            minDeliveryTime: 34,
            maxDeliveryTime: 34,
            lastMileTravel: 6.599999904632568,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.1",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "517611",
          name: "Hawtdog",
          uuid: "5928b7b0-ae73-4bed-b959-f643e3664d47",
          city: "13",
          area: "Thevara",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "vqey21jpxy4zbixs5x56",
          cuisines: ["Fast Food"],
          tags: [],
          costForTwo: 18000,
          costForTwoString: "₹180 FOR TWO",
          deliveryTime: 39,
          minDeliveryTime: 39,
          maxDeliveryTime: 39,
          slaString: "39 MINS",
          lastMileTravel: 5.800000190734863,
          slugs: {
            restaurant: "hawtdog-panampilly-nagar-panampilly-nagar",
            city: "kochi",
          },
          cityState: "13",
          address:
            "SKFWA 103 Association Road, Pandarachira Rd, Near Kallupalam, Kadavanthra, Kochi, Kerala 682020, India",
          locality: "Association Road",
          parentId: 309196,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "20% off",
            shortDescriptionList: [
              {
                meta: "20% off | Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "20% off up to ₹50 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "20% OFF",
            shortDescriptionList: [
              {
                meta: "Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "20% off up to ₹50 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 6500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 6500,
            message: "",
            title: "Delivery Charge",
            amount: "6500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "517611",
            deliveryTime: 39,
            minDeliveryTime: 39,
            maxDeliveryTime: 39,
            lastMileTravel: 5.800000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.3",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "625234",
          name: "The Paan Studio\t",
          uuid: "1a38a985-b586-4bc3-a8c5-ed57543cc624",
          city: "13",
          area: "Panampilly Nagar",
          totalRatingsString: "Too Few Ratings",
          cloudinaryImageId: "gp9lmvbr3wu1379spuva",
          cuisines: ["Paan"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          slaString: "27 MINS",
          lastMileTravel: 5.699999809265137,
          slugs: {
            restaurant: "the-paan-studio-panampilly-nagar-panampilly-nagar",
            city: "kochi",
          },
          cityState: "13",
          address:
            "55/414,PLOT NO 27A,PANAMPILLY NAGAR, Thrikkakara Circle, Ernakulam, Kerala-682036",
          locality: "Thrikkakara Circle",
          parentId: 212202,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "10% off",
            shortDescriptionList: [
              {
                meta: "10% off | Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "10% off | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "10% OFF",
            shortDescriptionList: [
              {
                meta: "Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "10% off | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 6500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 6500,
            message: "",
            title: "Delivery Charge",
            amount: "6500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "Closes soon",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.6 kms",
          hasSurge: false,
          sla: {
            restaurantId: "625234",
            deliveryTime: 27,
            minDeliveryTime: 27,
            maxDeliveryTime: 27,
            lastMileTravel: 5.699999809265137,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "--",
          totalRatings: 0,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "72177",
          name: "Punjabi Dhaba",
          uuid: "a9a4c7ae-8f39-44fe-aa72-fcde71a5731b",
          city: "13",
          area: "Pallimukku",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "ilyuo6uy9ciixeu1jjq0",
          cuisines: ["North Indian"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          slaString: "31 MINS",
          lastMileTravel: 6.300000190734863,
          slugs: {
            restaurant: "punjabi-dhaba-pallimukku-mg-road",
            city: "kochi",
          },
          cityState: "13",
          address:
            "Anand Bazar Pure Vej Restaurant ,First Floor ,Metro Pillar No 734, South Railway Station Road , Ernakulam ",
          locality: "Mg Road",
          parentId: 1476,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "FLAT100 off",
            shortDescriptionList: [
              {
                meta: "FLAT100 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "FLAT100 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹100 OFF",
            shortDescriptionList: [
              {
                meta: "Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "FLAT100 off | Use FLATDEAL",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 7500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 7500,
            message: "",
            title: "Delivery Charge",
            amount: "7500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "6.3 kms",
          hasSurge: false,
          sla: {
            restaurantId: "72177",
            deliveryTime: 31,
            minDeliveryTime: 31,
            maxDeliveryTime: 31,
            lastMileTravel: 6.300000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.9",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "367962",
          name: "La Pino'z Pizza",
          uuid: "53cc1763-0eec-4f39-be20-459de9296bb5",
          city: "13",
          area: "MKV Building",
          totalRatingsString: "5000+ ratings",
          cloudinaryImageId: "fallovrabd8hftqphizq",
          cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          slaString: "33 MINS",
          lastMileTravel: 7.099999904632568,
          slugs: {
            restaurant: "la-pino'z-pizza-kaloor-kaloor",
            city: "kochi",
          },
          cityState: "13",
          address:
            "1st floor MKV building, pillar number 687 MG road, near shehnoys theatre Ernakulam",
          locality: "Elamkulam",
          parentId: 4961,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "Flat ₹125 off",
            shortDescriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹125 OFF",
            shortDescriptionList: [
              {
                meta: "Use MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 8500,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 8500,
            message: "",
            title: "Delivery Charge",
            amount: "8500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7 kms",
          hasSurge: false,
          sla: {
            restaurantId: "367962",
            deliveryTime: 33,
            minDeliveryTime: 33,
            maxDeliveryTime: 33,
            lastMileTravel: 7.099999904632568,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.2",
          totalRatings: 5000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "511363",
          name: "Bektash Turkish Cafe",
          uuid: "17728dd4-4293-428f-9501-ad404147d77c",
          city: "13",
          area: "Chittoor Road",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "enzqlwh7owwhdgms60qc",
          cuisines: [
            "Snacks",
            "Juices",
            "Fast Food",
            "Arabian",
            "Turkish",
            "American",
            "Beverages",
          ],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          slaString: "30 MINS",
          lastMileTravel: 7.099999904632568,
          slugs: {
            restaurant: "bektash-turkish-cafe-kaloor-kaloor",
            city: "kochi",
          },
          cityState: "13",
          address:
            "66/3491 YMCA Jn, Shenoys Rd, Eranakulam Circle, Ernakulam, Kerala - 682035",
          locality: "Shenoys Road",
          parentId: 43111,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "30% off",
            shortDescriptionList: [
              {
                meta: "30% off | Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "30% off up to ₹75 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "30% OFF",
            shortDescriptionList: [
              {
                meta: "Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "30% off up to ₹75 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 8500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 8500,
            message: "",
            title: "Delivery Charge",
            amount: "8500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7 kms",
          hasSurge: false,
          sla: {
            restaurantId: "511363",
            deliveryTime: 30,
            minDeliveryTime: 30,
            maxDeliveryTime: 30,
            lastMileTravel: 7.099999904632568,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.2",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "306721",
          name: "Cafe Durbar AFC",
          uuid: "8d1d3e62-d198-49fe-ba64-ad7e8e4b0f68",
          city: "13",
          area: "Pallimukku",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "oc2m0ocyii9obajywk8w",
          cuisines: ["Beverages", "Juices", "Continental"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          slaString: "33 MINS",
          lastMileTravel: 6.400000095367432,
          slugs: {
            restaurant: "cafe-durbar-afc-panampilly-nagar-panampilly-nagar",
            city: "kochi",
          },
          cityState: "13",
          address:
            "DURBAR\tCAFE,62/753,DH\tROAD,ERNAKULAM\tSOUTH,\tERANAKULAM CIRCLE,\tERNAKULAM\t,\tKochi\t-\t682016",
          locality: "Dh Road",
          parentId: 52993,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "10% off",
            shortDescriptionList: [
              {
                meta: "10% off | Use MATCHPARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "10% off | Use code MATCHPARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "10% OFF",
            shortDescriptionList: [
              {
                meta: "Use MATCHPARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "10% off | Use code MATCHPARTY",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 7500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 7500,
            message: "",
            title: "Delivery Charge",
            amount: "7500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "6.4 kms",
          hasSurge: false,
          sla: {
            restaurantId: "306721",
            deliveryTime: 33,
            minDeliveryTime: 33,
            maxDeliveryTime: 33,
            lastMileTravel: 6.400000095367432,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.1",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "281168",
          name: "THAAL KITCHEN",
          uuid: "fdec3b6b-3802-4da1-9369-180fcdaaa2d3",
          city: "13",
          area: "MG Road",
          totalRatingsString: "5000+ ratings",
          cloudinaryImageId: "mcfygm91wklkxgsawnrw",
          cuisines: ["Kerala"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          slaString: "36 MINS",
          lastMileTravel: 7.800000190734863,
          slugs: {
            restaurant: "thaal-kitchen-kaloor-kaloor",
            city: "kochi",
          },
          cityState: "13",
          address:
            "66/4557 NEAR PADMA THEATRE M G ROAD, , ERNAKULAM CIRCLE, Kochi - 682016",
          locality: "Mahatma Gandhi Road",
          parentId: 20290,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "Flat ₹125 off",
            shortDescriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹125 OFF",
            shortDescriptionList: [
              {
                meta: "Use MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 8500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 8500,
            message: "",
            title: "Delivery Charge",
            amount: "8500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "281168",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 7.800000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.0",
          totalRatings: 5000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "668363",
          name: "Messy pots kitchen",
          uuid: "76e3a8a1-99d9-42fe-9a78-be243e5d5582",
          city: "13",
          area: "Panampilly Nagar",
          totalRatingsString: "20+ ratings",
          cloudinaryImageId: "b8fee70dcd2f7f43efe87cb2bdba64f3",
          cuisines: ["Fast Food", "Snacks", "Pastas"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          slaString: "38 MINS",
          lastMileTravel: 6.5,
          slugs: {
            restaurant: "messy-pots-kitchen-panampilly-nagar-panampilly-nagar",
            city: "kochi",
          },
          cityState: "13",
          address:
            "CRA-74, Neptune Country, Chilavannoor, Kochi, Kerala 682020, India",
          locality: "Chilavannoor",
          parentId: 400767,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "20% off",
            shortDescriptionList: [
              {
                meta: "20% off | Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "20% off up to ₹50 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "20% OFF",
            shortDescriptionList: [
              {
                meta: "Use TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "20% off up to ₹50 | Use code TRYNEW",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 7500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 7500,
            message: "",
            title: "Delivery Charge",
            amount: "7500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "6.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "668363",
            deliveryTime: 38,
            minDeliveryTime: 38,
            maxDeliveryTime: 38,
            lastMileTravel: 6.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.7",
          totalRatings: 20,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "57240",
          name: "McDonald's",
          uuid: "8c1dae04-fa60-4322-94fc-19fe9422d395",
          city: "13",
          area: "MG Road",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "ee5f8e06b300efc07c9fe3f4df40dfc4",
          cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          slaString: "36 MINS",
          lastMileTravel: 7.5,
          slugs: {
            restaurant: "mcdonalds-cochin-mg-road-mg-road",
            city: "kochi",
          },
          cityState: "13",
          address:
            "Hardcastle Restaurants Pvt Ltd, McDonalds Family Restaurants Pvt Ltd, Near Ravi?s Arcade, Next to Citi Bank,Padma Junction, M.G. Road,Cochin,Kerala ? 682035",
          locality: "Padma Junction",
          parentId: 630,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 8500,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 8500,
            message: "",
            title: "Delivery Charge",
            amount: "8500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "Closes soon",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "57240",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 7.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.3",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "54671",
          name: "Ceylon Bake House - Marine Drive",
          uuid: "37371d7f-1f9e-4124-a844-3f6a47e19b84",
          city: "13",
          area: "Marine Drive",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "mdqqdkcen1qkgsevb3fw",
          cuisines: ["South Indian", "North Indian", "Chinese"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          slaString: "37 MINS",
          lastMileTravel: 7.800000190734863,
          slugs: {
            restaurant:
              "ceylon-bake-house-near-guest-house-broad-way-ernakulam-mg-road",
            city: "kochi",
          },
          cityState: "13",
          address: "near guest house , broad way, ernakulam",
          locality: "Press Club Road",
          parentId: 19029,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "Flat ₹125 off",
            shortDescriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "₹125 OFF",
            shortDescriptionList: [
              {
                meta: "Use MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
                discountType: "Flat",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 8500,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 8500,
            message: "",
            title: "Delivery Charge",
            amount: "8500",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7.8 kms",
          hasSurge: false,
          sla: {
            restaurantId: "54671",
            deliveryTime: 37,
            minDeliveryTime: 37,
            maxDeliveryTime: 37,
            lastMileTravel: 7.800000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.1",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
  ];

export const ImageURL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/"